### ISSUE TITLE
Improve rewired input handling

### ISSUE THREAD

**Issue by BrandenEK** [NeonPixels/blasphemous.iter-tormenti#1]
https://github.com/NeonPixels/blasphemous.iter-tormenti/blob/7d4fba91da99754a80cd8fb40b8e0193b98d1b5f/IterTormenti/GamePatches.cs#L115

Every mod actually has its own property called "Input" for handling in-game input, so that you never have to interface directly with rewired.  An example of this can be found in the double jump mod (https://github.com/BrandenEK/Blasphemous-Double-Jump/blob/253ffdc04892cf55d1f6f4fd5557e0072c5e8e70/BlasDoubleJump/JumpController.cs#L45C1-L53C14)

**Comment by NeonPixels** [comment]
The problem is that `Input.GetButtonDown(InputHandler.ButtonCode.UIOptions)` gives me an error because 'Input.GetButton' expects an string value.

**Comment by BrandenEK** [comment]
That is because I made a poor decision when implementing the InputHandler.  'Input' is referring to the unityengine static class.  You will have to specifiy "Main.IterTormenti.Input" and then the method that takes in a button code

**Comment by NeonPixels** [comment]
Done! Thanks for the input!
